import { Categoria, Produto, ConfiguracoesSite, OrdemServico, Cliente, MovimentacaoEstoque } from "./types";

export const INITIAL_CATEGORIAS: Categoria[] = [
  {
    id: "cat-1",
    nome: "Smartphones",
    slug: "smartphones",
    descricao: "iPhones, Samsung Galaxy, Xiaomi e outros smartphones novos e seminovos revisados com garantia.",
    ativo: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-2",
    nome: "Acessórios",
    slug: "acessorios",
    descricao: "Capas de proteção, películas 3D/cerâmica, carregadores turbo homologados, cabos e suportes veiculares.",
    ativo: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-3",
    nome: "Informática & Notebooks",
    slug: "informatica-notebooks",
    descricao: "Notebooks, SSDs, memórias RAM, fontes e periféricos de alta performance.",
    ativo: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-4",
    nome: "Videogames & Consoles",
    slug: "videogames-consoles",
    descricao: "Controles originais, cabos HDMI 2.1, jogos e acessórios para PS5, Xbox e Nintendo Switch.",
    ativo: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-5",
    nome: "Áudio & Fones",
    slug: "audio-fones",
    descricao: "Fones de ouvido Bluetooth TWS, caixas de som portáteis e headsets gamer.",
    ativo: true,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_PRODUTOS: Produto[] = [
  {
    id: "prod-1",
    categoria_id: "cat-1",
    nome: "iPhone 13 128GB Estelar - Excelente Estado",
    marca: "Apple",
    modelo: "iPhone 13 128GB",
    sku: "IPH13-128-EST",
    slug: "iphone-13-128gb-estelar",
    descricao: "Aparelho 100% testado pela bancada Central Phones com 3 meses de garantia. Saúde da bateria acima de 85%, tela e carcaça originais impecáveis. Acompanha cabo Lightning e fonte turbo.",
    preco_custo: 2400.00,
    preco_venda: 3190.00,
    estoque_atual: 4,
    estoque_minimo: 1,
    destaque: true,
    ativo: true,
    foto_principal: "https://images.unsplash.com/photo-1591337676887-a217a6970a8a?w=800&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-2",
    categoria_id: "cat-1",
    nome: "Samsung Galaxy S23 128GB Preto Phantom",
    marca: "Samsung",
    modelo: "Galaxy S23 5G",
    sku: "SAMS23-128-PRT",
    slug: "samsung-galaxy-s23-128gb-preto",
    descricao: "Desempenho Snapdragon 8 Gen 2, câmera tripla de 50MP com Nightography espetacular. Aparelho em estado de novo, completo com caixa e carregador rápido 25W.",
    preco_custo: 2100.00,
    preco_venda: 2799.00,
    estoque_atual: 3,
    estoque_minimo: 1,
    destaque: true,
    ativo: true,
    foto_principal: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-3",
    categoria_id: "cat-2",
    nome: "Carregador Turbo Power 30W USB-C Homologado Anatel",
    marca: "Central Tech",
    modelo: "CP-30W-PD",
    sku: "CARG-30W-USBC",
    slug: "carregador-turbo-power-30w-usb-c",
    descricao: "Carregador com tecnologia Power Delivery 30W e Quick Charge 4.0. Proteção térmica contra sobretensão e curto-circuito. Ideal para iPhone, Samsung e Motorola.",
    preco_custo: 28.00,
    preco_venda: 69.90,
    estoque_atual: 18,
    estoque_minimo: 5,
    destaque: true,
    ativo: true,
    foto_principal: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-4",
    categoria_id: "cat-2",
    nome: "Cabo Reforçado Nylon Trançado USB-C para Lightning 1.2m",
    marca: "Baseus",
    modelo: "Cafule 20W",
    sku: "CAB-NYL-USBC-LGHT",
    slug: "cabo-reforcado-nylon-usb-c-lightning",
    descricao: "Cabo ultra durável com blindagem em liga de zinco e malha de nylon de alta densidade. Suporta carregamento rápido de até 20W e transferência de dados em 480 Mbps.",
    preco_custo: 18.00,
    preco_venda: 45.00,
    estoque_atual: 24,
    estoque_minimo: 6,
    destaque: false,
    ativo: true,
    foto_principal: "https://images.unsplash.com/photo-1541658016709-82535e94bc69?w=800&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-5",
    categoria_id: "cat-4",
    nome: "Controle DualSense PS5 Sem Fio Midnight Black",
    marca: "Sony PlayStation",
    modelo: "CFI-ZCT1W",
    sku: "PS5-DUAL-BLK",
    slug: "controle-dualsense-ps5-midnight-black",
    descricao: "Resposta tátil imersiva, gatilhos adaptáveis dinâmicos e microfone embutido. Produto original lacrado com garantia de 1 ano.",
    preco_custo: 330.00,
    preco_venda: 429.90,
    estoque_atual: 5,
    estoque_minimo: 2,
    destaque: true,
    ativo: true,
    foto_principal: "https://images.unsplash.com/photo-1606318801954-d46d46d3360a?w=800&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "prod-6",
    categoria_id: "cat-3",
    nome: "SSD Kingston NV2 1TB M.2 2280 NVMe PCIe 4.0",
    marca: "Kingston",
    modelo: "SNV2S/1000G",
    sku: "SSD-NV2-1TB",
    slug: "ssd-kingston-nv2-1tb-nvme",
    descricao: "Velocidades de leitura de até 3.500 MB/s e gravação de 2.100 MB/s. Dê uma vida nova ao seu notebook ou computador gamer com inicialização instantânea de softwares.",
    preco_custo: 290.00,
    preco_venda: 399.00,
    estoque_atual: 8,
    estoque_minimo: 2,
    destaque: false,
    ativo: true,
    foto_principal: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_CONFIG: ConfiguracoesSite = {
  id: "central_phones",
  nome_empresa: "Central Phones",
  logo_url: "/images/logo-central-phones.jpeg",
  imagem_hero: null,
  texto_apresentacao: "A Central Phones cuida do seu celular, notebook, videogame e eletrônicos com atendimento especializado, transparência e qualidade em São João del-Rei.",
  whatsapp: "5532935054792",
  instagram: "centralphones_sjdr",
  email: "contato@centralphones.com.br",
  endereco: "Avenida Sete de Setembro, nº 153",
  bairro: "Bairro Matozinhos",
  cidade_estado: "São João del-Rei – MG",
  cep: "CEP 36305-134",
  horario_funcionamento: "Segunda a Sexta: 08:30 às 18:00 | Sábado: 08:30 às 12:30",
  texto_sobre: "A Central Phones nasceu para oferecer tecnologia, assistência técnica de alto nível e atendimento de qualidade em São João del-Rei. Nosso laboratório conta com instrumentação de ponta, microscópios e estações de solda especializadas para resolver desde uma simples troca de tela até reparos avançados de placa em smartphones, computadores e consoles.",
  servicos_json: [
    {
      icone: "📱",
      titulo: "Troca de Tela",
      descricao: "Substituição de telas quebradas ou touch danificado com peças de altíssima qualidade, vedação e garantia.",
    },
    {
      icone: "🔋",
      titulo: "Troca de Bateria",
      descricao: "Recupere a autonomia e a saúde do seu aparelho sem superaquecimento ou desligamentos repentinos.",
    },
    {
      icone: "🔧",
      titulo: "Reparo de Placa",
      descricao: "Diagnóstico avançado por imagem térmica e microssoldagem para aparelhos que não ligam ou molharam.",
    },
    {
      icone: "💻",
      titulo: "Notebooks & Computadores",
      descricao: "Formatação limpa, troca de pasta térmica de prata, upgrades de SSD/RAM e recuperação de dados.",
    },
    {
      icone: "🎮",
      titulo: "Videogames & Consoles",
      descricao: "Limpeza preventiva completa em PS4, PS5, Xbox e reparo de analógicos drift em controles.",
    },
    {
      icone: "🛠️",
      titulo: "Manutenção Geral",
      descricao: "Troca de conectores de carga, alto-falantes, botões, microfones e reparos de carcaça.",
    },
  ],
  diferenciais_json: [
    "Orçamento prévio detalhado e transparente",
    "Técnicos especializados e certificados",
    "Garantia em todos os serviços realizados",
    "Peças selecionadas com procedência garantida",
  ],
  updated_at: new Date().toISOString(),
};

export const INITIAL_CLIENTES: Cliente[] = [
  {
    id: "cli-1",
    nome: "Carlos Eduardo Silva",
    telefone: "(32) 99876-5432",
    whatsapp: "5532998765432",
    email: "carlos.silva@gmail.com",
    cpf: "123.456.789-00",
    endereco: "Centro, São João del-Rei - MG",
    observacoes: "Cliente antigo, prefere contato após as 14h.",
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "cli-2",
    nome: "Mariana Costa Resende",
    telefone: "(32) 98811-2233",
    whatsapp: "5532988112233",
    email: "mariana.resende@outlook.com",
    cpf: "987.654.321-11",
    endereco: "Matosinhos, São João del-Rei - MG",
    observacoes: "Notebook de trabalho, urgência no reparo.",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_ORDENS: OrdemServico[] = [
  {
    id: "os-1",
    numero_os: 1001,
    cliente_id: "cli-1",
    tipo_atendimento: "delivery",
    endereco_coleta: "Rua Ministro Gabriel Passos, 210",
    bairro_coleta: "Centro",
    complemento_coleta: "Apto 302",
    ponto_referencia_coleta: "Próximo à Igreja Matriz",
    data_prevista_coleta: new Date(Date.now() - 2 * 86400000).toISOString().split("T")[0],
    periodo_coleta: "Tarde (14h às 18h)",
    data_prevista_entrega: new Date().toISOString().split("T")[0],
    taxa_deslocamento: 15.00,
    observacoes_delivery: "Portaria eletrônica, interfone 302.",
    status_coleta: "Coletado",
    status_entrega: "Pronto para entrega",
    tipo_aparelho: "Celular",
    marca: "Apple",
    modelo: "iPhone 11 64GB Preto",
    imei_serie: "358741098234120",
    senha_aparelho: "Sem senha (aparelho resetado)",
    defeito_relatado: "Aparelho caiu no chão, tela trincou e o touch parou de responder em algumas faixas.",
    estado_fisico: "Arranhões leves nas bordas, vidro frontal trincado.",
    acessorios_entregues: "Apenas o aparelho sem capa nem chip.",
    diagnostico: "Display LCD danificado pelo impacto. Conectores e placa-mãe intactos.",
    servico_realizar: "Substituição do módulo frontal completo (Display + Touch) e aplicação de película 3D cortesia.",
    valor_estimado: 380.00,
    valor_final: 395.00,
    status: "pronta",
    data_entrada: new Date(Date.now() - 2 * 86400000).toISOString(),
    prazo_estimado: new Date().toISOString().split("T")[0],
    data_conclusao: new Date().toISOString(),
    observacoes_internas: "Tela Premium linha ouro instalada e testada. True Tone transferido com sucesso. Agendar rota de retorno.",
    responsavel_nome: "Jonh Silva",
    fotos: [],
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "os-2",
    numero_os: 1002,
    cliente_id: "cli-2",
    tipo_atendimento: "balcao",
    endereco_coleta: null,
    bairro_coleta: null,
    complemento_coleta: null,
    ponto_referencia_coleta: null,
    data_prevista_coleta: null,
    periodo_coleta: null,
    data_prevista_entrega: null,
    taxa_deslocamento: 0,
    observacoes_delivery: null,
    status_coleta: null,
    status_entrega: null,
    tipo_aparelho: "Notebook",
    marca: "Dell",
    modelo: "Inspiron 15 3000 i5",
    imei_serie: "BR-59483201-DELL",
    senha_aparelho: "1234",
    defeito_relatado: "Notebook muito lento para ligar, esquentando bastante e desligando sozinho após 30 minutos.",
    estado_fisico: "Bom estado geral, carcaça sem quebras.",
    acessorios_entregues: "Carregador original Dell 65W.",
    diagnostico: "HD mecânico antigo com setores defeituosos e pasta térmica ressecada com acúmulo de poeira no cooler.",
    servico_realizar: "Upgrade para SSD 480GB NVMe, formatação com Windows 11 ativado, e limpeza interna com troca de pasta térmica Artic Silver.",
    valor_estimado: 450.00,
    valor_final: 450.00,
    status: "em_reparo",
    data_entrada: new Date(Date.now() - 1 * 86400000).toISOString(),
    prazo_estimado: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    data_conclusao: null,
    observacoes_internas: "Backup de fotos do cliente concluído com sucesso. Instalando sistema.",
    responsavel_nome: "Jonh Silva",
    fotos: [],
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_MOVIMENTACOES: MovimentacaoEstoque[] = [
  {
    id: "mov-1",
    produto_id: "prod-1",
    tipo: "entrada",
    quantidade: 5,
    estoque_anterior: 0,
    estoque_posterior: 5,
    motivo: "Estoque Inicial / Aquisição de Fornecedor",
    observacao: "Lote de seminovos grau A",
    usuario_email: "jonh@centralphones.com.br",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "mov-2",
    produto_id: "prod-1",
    tipo: "saida",
    quantidade: 1,
    estoque_anterior: 5,
    estoque_posterior: 4,
    motivo: "Venda direta balcão",
    observacao: "Cliente pagou via PIX",
    usuario_email: "jonh@centralphones.com.br",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];
